#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/global/cscratch1/sd/mikelam/nrn-7.6"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/global/cscratch1/sd/mikelam/nrn-7.6/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/global/u1/m/mikelam/vclamp/x86_64/.libs/libnrnmech.so" "$@"
